// <auto-generated>
/*
 * Hetzner Cloud API
 *
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: 0.22.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization.Metadata;
using Hetzner.Cloud.Client;

namespace Hetzner.Cloud.Model
{
    /// <summary>
    /// Request for POST https://api.hetzner.cloud/v1/servers/{id}/actions/add_to_placement_group
    /// </summary>
    internal partial class AddServerToPlacementGroupRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AddServerToPlacementGroupRequest" /> class.
        /// </summary>
        /// <param name="placementGroup">ID of Placement Group the Server should be added to</param>
        [JsonConstructor]
        internal AddServerToPlacementGroupRequest(long placementGroup)
        {
            PlacementGroup = placementGroup;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// ID of Placement Group the Server should be added to
        /// </summary>
        /// <value>ID of Placement Group the Server should be added to</value>
        /* <example>1</example> */
        [JsonPropertyName("placement_group")]
        public long PlacementGroup { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AddServerToPlacementGroupRequest {\n");
            sb.Append("  PlacementGroup: ").Append(PlacementGroup).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="AddServerToPlacementGroupRequest" />
    /// </summary>
    internal class AddServerToPlacementGroupRequestJsonConverter : JsonConverter<AddServerToPlacementGroupRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="AddServerToPlacementGroupRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override AddServerToPlacementGroupRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<long?> placementGroup = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "placement_group":
                            placementGroup = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!placementGroup.IsSet)
                throw new ArgumentException("Property is required for class AddServerToPlacementGroupRequest.", nameof(placementGroup));

            if (placementGroup.IsSet && placementGroup.Value == null)
                throw new ArgumentNullException(nameof(placementGroup), "Property is not nullable for class AddServerToPlacementGroupRequest.");

            return new AddServerToPlacementGroupRequest(placementGroup.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="AddServerToPlacementGroupRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="addServerToPlacementGroupRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, AddServerToPlacementGroupRequest addServerToPlacementGroupRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, addServerToPlacementGroupRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="AddServerToPlacementGroupRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="addServerToPlacementGroupRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, AddServerToPlacementGroupRequest addServerToPlacementGroupRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteNumber("placement_group", addServerToPlacementGroupRequest.PlacementGroup);
        }
    }

    /// <summary>
    /// The AddServerToPlacementGroupRequestSerializationContext
    /// </summary>
    [JsonSourceGenerationOptions(WriteIndented = true, GenerationMode = JsonSourceGenerationMode.Metadata | JsonSourceGenerationMode.Serialization)]
    [JsonSerializable(typeof(AddServerToPlacementGroupRequest))]
    internal partial class AddServerToPlacementGroupRequestSerializationContext : JsonSerializerContext { }
}
