// <auto-generated>
/*
 * Hetzner Cloud API
 *
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: 0.22.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization.Metadata;
using Hetzner.Cloud.Client;

namespace Hetzner.Cloud.Model
{
    /// <summary>
    /// Type of cpu architecture this iso is compatible with. Null indicates no restriction on the architecture (wildcard).
    /// </summary>
    /// <value>Type of cpu architecture this iso is compatible with. Null indicates no restriction on the architecture (wildcard).</value>
    internal enum ArchitectureOptional
    {
        /// <summary>
        /// Enum Arm for value: arm
        /// </summary>
        Arm = 1,

        /// <summary>
        /// Enum X86 for value: x86
        /// </summary>
        X86 = 2
    }

    /// <summary>
    /// Converts <see cref="ArchitectureOptional"/> to and from the JSON value
    /// </summary>
    public static class ArchitectureOptionalValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="ArchitectureOptional"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static ArchitectureOptional FromString(string value)
        {
            if (value.Equals("arm"))
                return ArchitectureOptional.Arm;

            if (value.Equals("x86"))
                return ArchitectureOptional.X86;

            throw new NotImplementedException($"Could not convert value to type ArchitectureOptional: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="ArchitectureOptional"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static ArchitectureOptional? FromStringOrDefault(string value)
        {
            if (value.Equals("arm"))
                return ArchitectureOptional.Arm;

            if (value.Equals("x86"))
                return ArchitectureOptional.X86;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="ArchitectureOptional"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ToJsonValue(ArchitectureOptional value)
        {
            if (value == ArchitectureOptional.Arm)
                return "arm";

            if (value == ArchitectureOptional.X86)
                return "x86";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ArchitectureOptional"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class ArchitectureOptionalJsonConverter : JsonConverter<ArchitectureOptional>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override ArchitectureOptional Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            ArchitectureOptional? result = rawValue == null
                ? null
                : ArchitectureOptionalValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the ArchitectureOptional to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="architectureOptional"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, ArchitectureOptional architectureOptional, JsonSerializerOptions options)
        {
            writer.WriteStringValue(architectureOptional.ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ArchitectureOptional"/>
    /// </summary>
    public class ArchitectureOptionalNullableJsonConverter : JsonConverter<ArchitectureOptional?>
    {
        /// <summary>
        /// Returns a ArchitectureOptional from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override ArchitectureOptional? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            ArchitectureOptional? result = rawValue == null
                ? null
                : ArchitectureOptionalValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the DateTime to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="architectureOptional"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, ArchitectureOptional? architectureOptional, JsonSerializerOptions options)
        {
            writer.WriteStringValue(architectureOptional?.ToString() ?? "null");
        }
    }


    /// <summary>
    /// The ArchitectureOptionalSerializationContext
    /// </summary>
    [JsonSourceGenerationOptions(WriteIndented = true, GenerationMode = JsonSourceGenerationMode.Metadata | JsonSourceGenerationMode.Serialization)]
    [JsonSerializable(typeof(ArchitectureOptional))]
    internal partial class ArchitectureOptionalSerializationContext : JsonSerializerContext { }
}
