// <auto-generated>
/*
 * Hetzner Cloud API
 *
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: 0.22.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization.Metadata;
using Hetzner.Cloud.Client;

namespace Hetzner.Cloud.Model
{
    /// <summary>
    /// Request for POST https://api.hetzner.cloud/v1/floating_ips/{id}/actions/assign
    /// </summary>
    internal partial class AssignFloatingIpToServerRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AssignFloatingIpToServerRequest" /> class.
        /// </summary>
        /// <param name="server">[Server](#servers) the [Floating IP](#floating-ips) is assigned to.  &#x60;null&#x60; if not assigned. </param>
        [JsonConstructor]
        internal AssignFloatingIpToServerRequest(long? server = default)
        {
            Server = server;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// [Server](#servers) the [Floating IP](#floating-ips) is assigned to.  &#x60;null&#x60; if not assigned. 
        /// </summary>
        /// <value>[Server](#servers) the [Floating IP](#floating-ips) is assigned to.  &#x60;null&#x60; if not assigned. </value>
        /* <example>42</example> */
        [JsonPropertyName("server")]
        public long? Server { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AssignFloatingIpToServerRequest {\n");
            sb.Append("  Server: ").Append(Server).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="AssignFloatingIpToServerRequest" />
    /// </summary>
    internal class AssignFloatingIpToServerRequestJsonConverter : JsonConverter<AssignFloatingIpToServerRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="AssignFloatingIpToServerRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override AssignFloatingIpToServerRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<long?> server = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "server":
                            server = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!server.IsSet)
                throw new ArgumentException("Property is required for class AssignFloatingIpToServerRequest.", nameof(server));

            return new AssignFloatingIpToServerRequest(server.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="AssignFloatingIpToServerRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="assignFloatingIpToServerRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, AssignFloatingIpToServerRequest assignFloatingIpToServerRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, assignFloatingIpToServerRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="AssignFloatingIpToServerRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="assignFloatingIpToServerRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, AssignFloatingIpToServerRequest assignFloatingIpToServerRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (assignFloatingIpToServerRequest.Server != null)
                writer.WriteNumber("server", assignFloatingIpToServerRequest.Server.Value);
            else
                writer.WriteNull("server");
        }
    }

    /// <summary>
    /// The AssignFloatingIpToServerRequestSerializationContext
    /// </summary>
    [JsonSourceGenerationOptions(WriteIndented = true, GenerationMode = JsonSourceGenerationMode.Metadata | JsonSourceGenerationMode.Serialization)]
    [JsonSerializable(typeof(AssignFloatingIpToServerRequest))]
    internal partial class AssignFloatingIpToServerRequestSerializationContext : JsonSerializerContext { }
}
