// <auto-generated>
/*
 * Hetzner Cloud API
 *
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: 0.22.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization.Metadata;
using Hetzner.Cloud.Client;

namespace Hetzner.Cloud.Model
{
    /// <summary>
    /// Request for POST https://api.hetzner.cloud/v1/networks/{id}/actions/change_protection
    /// </summary>
    internal partial class ChangeNetworkProtectionRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ChangeNetworkProtectionRequest" /> class.
        /// </summary>
        /// <param name="delete">Delete protection setting.  If true, prevents the [Network](#networks) from being deleted. </param>
        [JsonConstructor]
        internal ChangeNetworkProtectionRequest(Option<bool?> delete = default)
        {
            DeleteOption = delete;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Delete
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> DeleteOption { get; private set; }

        /// <summary>
        /// Delete protection setting.  If true, prevents the [Network](#networks) from being deleted. 
        /// </summary>
        /// <value>Delete protection setting.  If true, prevents the [Network](#networks) from being deleted. </value>
        /* <example>true</example> */
        [JsonPropertyName("delete")]
        public bool? Delete { get { return this.DeleteOption; } set { this.DeleteOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ChangeNetworkProtectionRequest {\n");
            sb.Append("  Delete: ").Append(Delete).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ChangeNetworkProtectionRequest" />
    /// </summary>
    internal class ChangeNetworkProtectionRequestJsonConverter : JsonConverter<ChangeNetworkProtectionRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="ChangeNetworkProtectionRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ChangeNetworkProtectionRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<bool?> delete = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "delete":
                            delete = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (delete.IsSet && delete.Value == null)
                throw new ArgumentNullException(nameof(delete), "Property is not nullable for class ChangeNetworkProtectionRequest.");

            return new ChangeNetworkProtectionRequest(delete);
        }

        /// <summary>
        /// Serializes a <see cref="ChangeNetworkProtectionRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="changeNetworkProtectionRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ChangeNetworkProtectionRequest changeNetworkProtectionRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, changeNetworkProtectionRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ChangeNetworkProtectionRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="changeNetworkProtectionRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ChangeNetworkProtectionRequest changeNetworkProtectionRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (changeNetworkProtectionRequest.DeleteOption.IsSet)
                writer.WriteBoolean("delete", changeNetworkProtectionRequest.DeleteOption.Value!.Value);
        }
    }

    /// <summary>
    /// The ChangeNetworkProtectionRequestSerializationContext
    /// </summary>
    [JsonSourceGenerationOptions(WriteIndented = true, GenerationMode = JsonSourceGenerationMode.Metadata | JsonSourceGenerationMode.Serialization)]
    [JsonSerializable(typeof(ChangeNetworkProtectionRequest))]
    internal partial class ChangeNetworkProtectionRequestSerializationContext : JsonSerializerContext { }
}
