// <auto-generated>
/*
 * Hetzner Cloud API
 *
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: 0.22.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization.Metadata;
using Hetzner.Cloud.Client;

namespace Hetzner.Cloud.Model
{
    /// <summary>
    /// Request for POST https://api.hetzner.cloud/v1/ssh_keys
    /// </summary>
    public partial class CreateSshKeyRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateSshKeyRequest" /> class.
        /// </summary>
        /// <param name="name">Name of the SSH key</param>
        /// <param name="publicKey">Public key</param>
        /// <param name="labels">User-defined labels (&#x60;key/value&#x60; pairs) for the Resource. For more information, see \&quot;[Labels](#labels)\&quot;. </param>
        [JsonConstructor]
        public CreateSshKeyRequest(string name, string publicKey, Option<Dictionary<string, string>?> labels = default)
        {
            Name = name;
            PublicKey = publicKey;
            LabelsOption = labels;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Name of the SSH key
        /// </summary>
        /// <value>Name of the SSH key</value>
        /* <example>My ssh key</example> */
        [JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>
        /// Public key
        /// </summary>
        /// <value>Public key</value>
        /* <example>ssh-rsa AAAjjk76kgf...Xt</example> */
        [JsonPropertyName("public_key")]
        public string PublicKey { get; set; }

        /// <summary>
        /// Used to track the state of Labels
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Dictionary<string, string>?> LabelsOption { get; private set; }

        /// <summary>
        /// User-defined labels (&#x60;key/value&#x60; pairs) for the Resource. For more information, see \&quot;[Labels](#labels)\&quot;. 
        /// </summary>
        /// <value>User-defined labels (&#x60;key/value&#x60; pairs) for the Resource. For more information, see \&quot;[Labels](#labels)\&quot;. </value>
        /* <example>{&quot;environment&quot;:&quot;prod&quot;,&quot;example.com/my&quot;:&quot;label&quot;,&quot;just-a-key&quot;:&quot;&quot;}</example> */
        [JsonPropertyName("labels")]
        public Dictionary<string, string>? Labels { get { return this.LabelsOption; } set { this.LabelsOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateSshKeyRequest {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  PublicKey: ").Append(PublicKey).Append("\n");
            sb.Append("  Labels: ").Append(Labels).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CreateSshKeyRequest" />
    /// </summary>
    public class CreateSshKeyRequestJsonConverter : JsonConverter<CreateSshKeyRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="CreateSshKeyRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override CreateSshKeyRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> name = default;
            Option<string?> publicKey = default;
            Option<Dictionary<string, string>?> labels = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "public_key":
                            publicKey = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "labels":
                            labels = new Option<Dictionary<string, string>?>(JsonSerializer.Deserialize<Dictionary<string, string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!name.IsSet)
                throw new ArgumentException("Property is required for class CreateSshKeyRequest.", nameof(name));

            if (!publicKey.IsSet)
                throw new ArgumentException("Property is required for class CreateSshKeyRequest.", nameof(publicKey));

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class CreateSshKeyRequest.");

            if (publicKey.IsSet && publicKey.Value == null)
                throw new ArgumentNullException(nameof(publicKey), "Property is not nullable for class CreateSshKeyRequest.");

            if (labels.IsSet && labels.Value == null)
                throw new ArgumentNullException(nameof(labels), "Property is not nullable for class CreateSshKeyRequest.");

            return new CreateSshKeyRequest(name.Value!, publicKey.Value!, labels);
        }

        /// <summary>
        /// Serializes a <see cref="CreateSshKeyRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="createSshKeyRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, CreateSshKeyRequest createSshKeyRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, createSshKeyRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="CreateSshKeyRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="createSshKeyRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, CreateSshKeyRequest createSshKeyRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (createSshKeyRequest.Name == null)
                throw new ArgumentNullException(nameof(createSshKeyRequest.Name), "Property is required for class CreateSshKeyRequest.");

            if (createSshKeyRequest.PublicKey == null)
                throw new ArgumentNullException(nameof(createSshKeyRequest.PublicKey), "Property is required for class CreateSshKeyRequest.");

            if (createSshKeyRequest.LabelsOption.IsSet && createSshKeyRequest.Labels == null)
                throw new ArgumentNullException(nameof(createSshKeyRequest.Labels), "Property is required for class CreateSshKeyRequest.");

            writer.WriteString("name", createSshKeyRequest.Name);

            writer.WriteString("public_key", createSshKeyRequest.PublicKey);

            if (createSshKeyRequest.LabelsOption.IsSet)
            {
                writer.WritePropertyName("labels");
                JsonSerializer.Serialize(writer, createSshKeyRequest.Labels, jsonSerializerOptions);
            }
        }
    }

    /// <summary>
    /// The CreateSshKeyRequestSerializationContext
    /// </summary>
    [JsonSourceGenerationOptions(WriteIndented = true, GenerationMode = JsonSourceGenerationMode.Metadata | JsonSourceGenerationMode.Serialization)]
    [JsonSerializable(typeof(CreateSshKeyRequest))]
    public partial class CreateSshKeyRequestSerializationContext : JsonSerializerContext { }
}
