// <auto-generated>
/*
 * Hetzner Cloud API
 *
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: 0.22.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization.Metadata;
using Hetzner.Cloud.Client;

namespace Hetzner.Cloud.Model
{
    /// <summary>
    /// Response to POST https://api.hetzner.cloud/v1/servers/{id}/actions/enable_rescue
    /// </summary>
    public partial class EnableRescueModeForServerResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EnableRescueModeForServerResponse" /> class.
        /// </summary>
        /// <param name="action">action</param>
        /// <param name="rootPassword">Password that will be set for this Server once the Action succeeds</param>
        [JsonConstructor]
        public EnableRescueModeForServerResponse(Option<Action?> action = default, Option<string?> rootPassword = default)
        {
            ActionOption = action;
            RootPasswordOption = rootPassword;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Action
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Action?> ActionOption { get; private set; }

        /// <summary>
        /// Gets or Sets Action
        /// </summary>
        [JsonPropertyName("action")]
        public Action? Action { get { return this.ActionOption; } set { this.ActionOption = new(value); } }

        /// <summary>
        /// Used to track the state of RootPassword
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> RootPasswordOption { get; private set; }

        /// <summary>
        /// Password that will be set for this Server once the Action succeeds
        /// </summary>
        /// <value>Password that will be set for this Server once the Action succeeds</value>
        /* <example>zCWbFhnu950dUTko5f40</example> */
        [JsonPropertyName("root_password")]
        public string? RootPassword { get { return this.RootPasswordOption; } set { this.RootPasswordOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EnableRescueModeForServerResponse {\n");
            sb.Append("  Action: ").Append(Action).Append("\n");
            sb.Append("  RootPassword: ").Append(RootPassword).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="EnableRescueModeForServerResponse" />
    /// </summary>
    public class EnableRescueModeForServerResponseJsonConverter : JsonConverter<EnableRescueModeForServerResponse>
    {
        /// <summary>
        /// Deserializes json to <see cref="EnableRescueModeForServerResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override EnableRescueModeForServerResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Action?> action = default;
            Option<string?> rootPassword = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "action":
                            action = new Option<Action?>(JsonSerializer.Deserialize<Action>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "root_password":
                            rootPassword = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (action.IsSet && action.Value == null)
                throw new ArgumentNullException(nameof(action), "Property is not nullable for class EnableRescueModeForServerResponse.");

            if (rootPassword.IsSet && rootPassword.Value == null)
                throw new ArgumentNullException(nameof(rootPassword), "Property is not nullable for class EnableRescueModeForServerResponse.");

            return new EnableRescueModeForServerResponse(action, rootPassword);
        }

        /// <summary>
        /// Serializes a <see cref="EnableRescueModeForServerResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="enableRescueModeForServerResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, EnableRescueModeForServerResponse enableRescueModeForServerResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, enableRescueModeForServerResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="EnableRescueModeForServerResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="enableRescueModeForServerResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, EnableRescueModeForServerResponse enableRescueModeForServerResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (enableRescueModeForServerResponse.ActionOption.IsSet && enableRescueModeForServerResponse.Action == null)
                throw new ArgumentNullException(nameof(enableRescueModeForServerResponse.Action), "Property is required for class EnableRescueModeForServerResponse.");

            if (enableRescueModeForServerResponse.RootPasswordOption.IsSet && enableRescueModeForServerResponse.RootPassword == null)
                throw new ArgumentNullException(nameof(enableRescueModeForServerResponse.RootPassword), "Property is required for class EnableRescueModeForServerResponse.");

            if (enableRescueModeForServerResponse.ActionOption.IsSet)
            {
                writer.WritePropertyName("action");
                JsonSerializer.Serialize(writer, enableRescueModeForServerResponse.Action, jsonSerializerOptions);
            }
            if (enableRescueModeForServerResponse.RootPasswordOption.IsSet)
                writer.WriteString("root_password", enableRescueModeForServerResponse.RootPassword);
        }
    }

    /// <summary>
    /// The EnableRescueModeForServerResponseSerializationContext
    /// </summary>
    [JsonSourceGenerationOptions(WriteIndented = true, GenerationMode = JsonSourceGenerationMode.Metadata | JsonSourceGenerationMode.Serialization)]
    [JsonSerializable(typeof(EnableRescueModeForServerResponse))]
    public partial class EnableRescueModeForServerResponseSerializationContext : JsonSerializerContext { }
}
