// <auto-generated>
/*
 * Hetzner Cloud API
 *
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: 0.22.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization.Metadata;
using Hetzner.Cloud.Client;

namespace Hetzner.Cloud.Model
{
    /// <summary>
    /// Response to GET https://api.hetzner.cloud/v1/certificates/{id}
    /// </summary>
    public partial class GetCertificateResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetCertificateResponse" /> class.
        /// </summary>
        /// <param name="certificate">certificate</param>
        [JsonConstructor]
        public GetCertificateResponse(Certificate certificate)
        {
            Certificate = certificate;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Certificate
        /// </summary>
        [JsonPropertyName("certificate")]
        public Certificate Certificate { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetCertificateResponse {\n");
            sb.Append("  Certificate: ").Append(Certificate).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="GetCertificateResponse" />
    /// </summary>
    public class GetCertificateResponseJsonConverter : JsonConverter<GetCertificateResponse>
    {
        /// <summary>
        /// Deserializes json to <see cref="GetCertificateResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override GetCertificateResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Certificate?> certificate = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "certificate":
                            certificate = new Option<Certificate?>(JsonSerializer.Deserialize<Certificate>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!certificate.IsSet)
                throw new ArgumentException("Property is required for class GetCertificateResponse.", nameof(certificate));

            if (certificate.IsSet && certificate.Value == null)
                throw new ArgumentNullException(nameof(certificate), "Property is not nullable for class GetCertificateResponse.");

            return new GetCertificateResponse(certificate.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="GetCertificateResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getCertificateResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, GetCertificateResponse getCertificateResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, getCertificateResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="GetCertificateResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getCertificateResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, GetCertificateResponse getCertificateResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (getCertificateResponse.Certificate == null)
                throw new ArgumentNullException(nameof(getCertificateResponse.Certificate), "Property is required for class GetCertificateResponse.");

            writer.WritePropertyName("certificate");
            JsonSerializer.Serialize(writer, getCertificateResponse.Certificate, jsonSerializerOptions);
        }
    }

    /// <summary>
    /// The GetCertificateResponseSerializationContext
    /// </summary>
    [JsonSourceGenerationOptions(WriteIndented = true, GenerationMode = JsonSourceGenerationMode.Metadata | JsonSourceGenerationMode.Serialization)]
    [JsonSerializable(typeof(GetCertificateResponse))]
    public partial class GetCertificateResponseSerializationContext : JsonSerializerContext { }
}
