// <auto-generated>
/*
 * Hetzner Cloud API
 *
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: 0.22.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization.Metadata;
using Hetzner.Cloud.Client;

namespace Hetzner.Cloud.Model
{
    /// <summary>
    /// MetricsTimeSeriesValue
    /// </summary>
    internal partial class MetricsTimeSeriesValue : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MetricsTimeSeriesValue" /> class.
        /// </summary>
        /// <param name="values">Metrics Timestamps with values</param>
        [JsonConstructor]
        internal MetricsTimeSeriesValue(List<List<MetricsTimeSeriesValue>> values)
        {
            Values = values;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Metrics Timestamps with values
        /// </summary>
        /// <value>Metrics Timestamps with values</value>
        [JsonPropertyName("values")]
        public List<List<MetricsTimeSeriesValue>> Values { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MetricsTimeSeriesValue {\n");
            sb.Append("  Values: ").Append(Values).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="MetricsTimeSeriesValue" />
    /// </summary>
    internal class MetricsTimeSeriesValueJsonConverter : JsonConverter<MetricsTimeSeriesValue>
    {
        /// <summary>
        /// Deserializes json to <see cref="MetricsTimeSeriesValue" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override MetricsTimeSeriesValue Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<List<List<MetricsTimeSeriesValue>>?> values = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "values":
                            values = new Option<List<List<MetricsTimeSeriesValue>>?>(JsonSerializer.Deserialize<List<List<MetricsTimeSeriesValue>>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!values.IsSet)
                throw new ArgumentException("Property is required for class MetricsTimeSeriesValue.", nameof(values));

            if (values.IsSet && values.Value == null)
                throw new ArgumentNullException(nameof(values), "Property is not nullable for class MetricsTimeSeriesValue.");

            return new MetricsTimeSeriesValue(values.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="MetricsTimeSeriesValue" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="metricsTimeSeriesValue"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, MetricsTimeSeriesValue metricsTimeSeriesValue, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, metricsTimeSeriesValue, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="MetricsTimeSeriesValue" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="metricsTimeSeriesValue"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, MetricsTimeSeriesValue metricsTimeSeriesValue, JsonSerializerOptions jsonSerializerOptions)
        {
            if (metricsTimeSeriesValue.Values == null)
                throw new ArgumentNullException(nameof(metricsTimeSeriesValue.Values), "Property is required for class MetricsTimeSeriesValue.");

            writer.WritePropertyName("values");
            JsonSerializer.Serialize(writer, metricsTimeSeriesValue.Values, jsonSerializerOptions);
        }
    }

    /// <summary>
    /// The MetricsTimeSeriesValueSerializationContext
    /// </summary>
    [JsonSourceGenerationOptions(WriteIndented = true, GenerationMode = JsonSourceGenerationMode.Metadata | JsonSourceGenerationMode.Serialization)]
    [JsonSerializable(typeof(MetricsTimeSeriesValue))]
    internal partial class MetricsTimeSeriesValueSerializationContext : JsonSerializerContext { }
}
