// <auto-generated>
/*
 * Hetzner Cloud API
 *
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: 0.22.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization.Metadata;
using Hetzner.Cloud.Client;

namespace Hetzner.Cloud.Model
{
    /// <summary>
    /// Response to PUT https://api.hetzner.cloud/v1/images/{id}
    /// </summary>
    public partial class ReplaceImageResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ReplaceImageResponse" /> class.
        /// </summary>
        /// <param name="image">image</param>
        [JsonConstructor]
        public ReplaceImageResponse(Option<Image?> image = default)
        {
            ImageOption = image;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Image
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Image?> ImageOption { get; private set; }

        /// <summary>
        /// Gets or Sets Image
        /// </summary>
        [JsonPropertyName("image")]
        public Image? Image { get { return this.ImageOption; } set { this.ImageOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ReplaceImageResponse {\n");
            sb.Append("  Image: ").Append(Image).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ReplaceImageResponse" />
    /// </summary>
    public class ReplaceImageResponseJsonConverter : JsonConverter<ReplaceImageResponse>
    {
        /// <summary>
        /// Deserializes json to <see cref="ReplaceImageResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ReplaceImageResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Image?> image = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "image":
                            image = new Option<Image?>(JsonSerializer.Deserialize<Image>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (image.IsSet && image.Value == null)
                throw new ArgumentNullException(nameof(image), "Property is not nullable for class ReplaceImageResponse.");

            return new ReplaceImageResponse(image);
        }

        /// <summary>
        /// Serializes a <see cref="ReplaceImageResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="replaceImageResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ReplaceImageResponse replaceImageResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, replaceImageResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ReplaceImageResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="replaceImageResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ReplaceImageResponse replaceImageResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (replaceImageResponse.ImageOption.IsSet && replaceImageResponse.Image == null)
                throw new ArgumentNullException(nameof(replaceImageResponse.Image), "Property is required for class ReplaceImageResponse.");

            if (replaceImageResponse.ImageOption.IsSet)
            {
                writer.WritePropertyName("image");
                JsonSerializer.Serialize(writer, replaceImageResponse.Image, jsonSerializerOptions);
            }
        }
    }

    /// <summary>
    /// The ReplaceImageResponseSerializationContext
    /// </summary>
    [JsonSourceGenerationOptions(WriteIndented = true, GenerationMode = JsonSourceGenerationMode.Metadata | JsonSourceGenerationMode.Serialization)]
    [JsonSerializable(typeof(ReplaceImageResponse))]
    public partial class ReplaceImageResponseSerializationContext : JsonSerializerContext { }
}
